### ISSUE TITLE
settings page not finished

### ISSUE THREAD

**Issue by VillainsRule** [Skoolgq/skoolv2#14]
settings.html doesn't work as it's cut off in the code
ss of deployment
![image](https://user-images.githubusercontent.com/101288516/224698023-e64cbaf3-bd24-4479-b984-09937c53fbfa.png)

this was taken from skool.lol ^^^

**Comment by fowntain** [comment]
> > Yeah, I couldn't get the cloaker to work.
> 
> what errors?

It just would not cloak the page. I didn't look in console for errors bc I didn't really care much at the time

**Comment by fowntain** [comment]
> want me to try to fix it? if you add the css to the page i'll try (i'm shit with css)

wdym if I add the css?

**Comment by fowntain** [comment]
Working on/completed
