### ISSUE TITLE
Links!

### ISSUE THREAD

**Issue by TrickJoker312** [Skoolgq/skoolv2#15]
hello! I was wondering if you have any more links for this site. I have a repository for unblocked sites for people to play games while at school. I'd appreciate it if you could link them below!

**Comment by fowntain** [comment]
> hello! I was wondering if you have any more links for this site. I have a repository for unblocked sites for people to play games while at school. I'd appreciate it if you could link them below!

Hi! If you join our [discord](https://discord.gg/skool), we have a channel called `#site-links` that you can use to get more of our links, but here's a few to get you started:
[learningabcto.xyz](https://learningabcto.xyz)
[skool.lol](https://skool.lol)
[mathwizard.pages.dev](https://mathwizard.pages.dev)
And then, of course, our main links:
[skool.world](https://skool.world)
[skoolgq.github.io](https://skoolgq.github.io)
